name: Rust

on:
  push:
    branches: [ "v1" ]
  pull_request:
    branches: [ "v1" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd safina_db
        cargo build --verbose
    - name: Run tests
      run: |
        cd safina_db
        cargo test --verbose
    - name: Generate Documentation
      run: |
        cd safina_db
        cargo doc --no-deps
